;;;;;;;;;;;;;;;;;;;;;;;;;;; -*- Mode: Emacs-Lisp -*- ;;;;;;;;;;;;;;;;;;;;;;;;;;
;; bk-point.inc -- Implement a bk-point librairy.
;; Programmed and contributed by Rachid Alami (LAAS/CNRS)
;; 
;; Copyright (C) 1996 Rachid Alami LAAS/CNRS.
;; 
;; Author          : Rachid Alami (alami@laas.fr)
;; Created On      : Mon Sep 30 14:00:34 1996
;; Last Modified By: Francois Felix Ingrand
;; Last Modified On: Thu Mar 20 16:38:50 1997
;; Update Count    : 5
;; Status          : OK
;; $Id$
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

require "new-default.inc"
require "quick-sort.inc"

include "bk-point.sym"
load opf "bk-point.opf"
