;;;;;;;;;;;;;;;;;;;;;;;;;;; -*- Mode: Emacs-Lisp -*- ;;;;;;;;;;;;;;;;;;;;;;;;;;
;; quick-sort.inc -- Implement a quick sort algorithm.
;; Programmed and contributed by Rachid Alami (LAAS/CNRS)
;; 
;; Copyright (C) 1996 Rachid Alami LAAS/CNRS.
;; 
;; Author          : Rachid Alami (alami@laas.fr)
;; Created On      : Mon Sep 30 14:00:34 1996
;; Last Modified By: Francois Felix Ingrand
;; Last Modified On: Thu Mar 20 16:38:48 1997
;; Update Count    : 4
;; Status          : OK
;; $Id$
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

include "quick-sort.sym"
load opf "quick-sort.opf"
