#!/bin/csh
if ($#argv != 2) then
     echo "Wrong arguments..."
er:
     echo "Usage: mk_oprs_bin_tree <absolute_source_dir> <config>" 
     exit(1)
endif

set srcdir=$argv[1]
set config=$argv[2]

if ( -f $srcdir/config/$config.make && -f  $srcdir/config/$config.h) then
	ln -s $srcdir/config/$config.make site.make
	ln -s $srcdir/config/$config.h config.h
else
	echo $srcdir/config/$config.make or  $srcdir/config/$config.h do not exists.
	echo The currently supported versions are:
	cd $srcdir/config
	foreach i (*.h)
		if ( -f `basename $i .h`.make ) echo `basename $i .h`
	end
	exit(1)
endif
echo Creating path.make
cat >path.make <<EOF
srctop = $srcdir
EOF
echo Linking Makefile
ln -s $srcdir/Makefile.dev Makefile
mkdir c_toolkit
ln -s $srcdir/c_toolkit/Makefile c_toolkit/Makefile
mkdir util
ln -s $srcdir/util/Makefile util/Makefile
mkdir contrib
mkdir contrib/src
ln -s $srcdir/contrib/src/Makefile contrib/src/Makefile
ln -s $srcdir/contrib/Makefile contrib/Makefile
ln -s $srcdir/contrib/data contrib/data
ln -s $srcdir/data data
mkdir doc
cd doc
lndir $srcdir/doc .
