include "new-default.sym"
load opf "new-default.opf"
declare symbol TEST-FACTORIAL
declare symbol IT-FACTORIAL
declare symbol PRINT-IT-FACTORIAL
declare symbol R-FACTORIAL
declare symbol GEN-N-FACTS
declare symbol GEN-NP-FACTS
declare symbol TEST-N-FACT
declare symbol TEST-NP-FACT
declare cwp STOP-MESSAGE
declare symbol TEST
declare symbol TEST-MESSAGE
load opf "probe.opf"
;compile_ops "probe-2.opf"
