/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.

 */
#ifndef __CEXTRACT__
#ifdef __STDC__

extern Term * PUMakeTermInteger ( int val );
extern Term* PUMakeTermFloat ( double val );
extern Term * PUMakeTermAtom ( char *atom );
extern Term* PUMakeTermUPointer ( void *pointer );
extern Term* PUMakeTermUMemory ( void *p, int size );
extern Term * PUMakeTermTrue ( void );
extern Term * PUMakeTermNil ( void );
extern Term *PUMakeTermString ( char *string );
extern Term * PUMakeTermLispList ( int NbTerm, ... );
extern Term * PUMakeTermComp ( Pred_Func_Rec* funcName, int NbTerm, ... );
extern Term * PUMakeExternalTermComp ( char* fName, int NbTerm, ... );
extern TermList PUMakeTermList ( int NbTerm, ... );
extern Term * PUMakeTermCList ( int NbTerm, ... );

#else /* __STDC__ */

extern Term * PUMakeTermInteger (/* int val */);
extern Term* PUMakeTermFloat (/* double val */);
extern Term * PUMakeTermAtom (/* char *atom */);
extern Term* PUMakeTermUPointer (/* void *pointer */);
extern Term* PUMakeTermUMemory (/* void *p, int size */);
extern Term * PUMakeTermTrue (/* void */);
extern Term * PUMakeTermNil (/* void */);
extern Term *PUMakeTermString (/* char *string */);
extern Term * PUMakeTermLispList (/* int NbTerm, ... */);
extern Term * PUMakeTermComp (/* Func_Rec* funcName, int NbTerm, ... */);
extern Term * PUMakeExternalTermComp (/* char* fName, int NbTerm, ... */);
extern TermList PUMakeTermList (/* int NbTerm, ... */);
extern Term * PUMakeTermCList (/* int NbTerm, ... */);

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
