/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.

 */
#ifdef __cplusplus
extern "C" {
#endif

#ifndef __CEXTRACT__
#ifdef __STDC__
/* Prototypes */

extern PBoolean PUGetOprsParameters ( TermList paramList, int NbParametres, ... );
extern PBoolean PUGetLispListElem ( L_List lispList, int NbTerm, ... );
extern int PUGetLispListCar ( L_List *lispListPtr, Term_Type type, void *ptr );
extern PBoolean PUGetOprsTermCompArgs ( Expression *tc, int NbParametres, ... );
extern PBoolean PUGetOprsTermCompSpecArg ( Expression *tc, int rank, Term_Type type, void *ptr );
extern PBoolean PUGetOprsParametersSpecArg ( TermList paramList, int rank, Term_Type type, void *ptr );

#else /* __STDC__ */

extern PBoolean PUGetOprsParameters (/* TermList paramList, int NbParametres, ... */);
extern PBoolean PUGetLispListElem (/* L_List lispList, int NbTerm, ... */);
extern int PUGetLispListCar (/* L_List *lispListPtr, Term_Type type, void *ptr */);
extern PBoolean PUGetOprsTermCompArgs (/* Expression *tc, int NbParametres, ... */);
extern PBoolean PUGetOprsTermCompSpecArg (/* Expression *tc, int rank, Term_Type type, void *ptr */);
extern PBoolean PUGetOprsParametersSpecArg (/* TermList paramList, int rank, Term_Type type, void *ptr */);

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
#ifdef __cplusplus
}
#endif
