/*
 *   This file was a long time ago automatically generated by version 1.7 of cextract.
 *   Manual editing has been done already...

 */
#ifdef __cplusplus
extern "C" {
#endif

/* Prototypes */

extern PBoolean PUGetOprsParameters ( TermList paramList, int NbParametres, ... );
extern PBoolean PUGetLispListElem ( L_List lispList, int NbTerm, ... );
extern int PUGetLispListCar ( L_List *lispListPtr, Term_Type type, void *ptr );
extern PBoolean PUGetOprsTermCompArgs ( Expression *tc, int NbParametres, ... );
extern PBoolean PUGetOprsTermCompSpecArg ( Expression *tc, int rank, Term_Type type, void *ptr );
extern PBoolean PUGetOprsParametersSpecArg ( TermList paramList, int rank, Term_Type type, void *ptr );
extern PBoolean PUGetOprsVarArgParameters(TermList paramList, PBoolean find_them_all, int nb, ...);

#define set_parameter_or_default_value(parameter,default_value,oprs_type) (parameter = (default_value),oprs_type),#parameter,&(parameter)

  

#ifdef __cplusplus
}
#endif
