void xp_create_trace_intention_dialog(Widget parent, Intention *in, char *title);
void xpShowIDialogManage(Intention *in);
void manage_ut_window(Widget w);
void unmanage_ut_window(Widget w);
void delete_ut_window(Widget w);
void rename_ut_window(Widget w, char *title);
void xpTraceIDialogUpdate(Widget w, char *string);
void resetQuestionManage(void);
void xp_create_showdb_dialog(Widget parent);
void xp_create_showig_dialog(Widget parent);
void xp_create_show_cond_dialog(Widget parent);
void xp_information_create(Widget parent);
void xpcreate_dialogs(Widget parent, Draw_Data *dd);
void xp_create_show_intention_dialog(Widget parent);
